### ISSUE TITLE
Link CocoaPods wrong

### ISSUE THREAD

**Issue by YannickSteph** [quickbirdstudios/RxCoordinator#10]
<img width="1007" alt="capture d ecran 2018-08-07 a 10 14 21" src="https://user-images.githubusercontent.com/6950194/43781370-bc66958e-9a2a-11e8-9aad-7b0115728882.png">

I have this error when i try to use with CocoaPods. And the link is not work.

**Comment by YannickSteph** [comment]
for that work i use that

`pod 'rx-coordinator', :git => 'https://github.com/quickbirdstudios/RxCoordinator.git'`

**Comment by sellmair** [comment]
@grafele Is this issue still relevant?

**Comment by grafele** [comment]
This should be fixed. Thanks for your feedback.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
