### ISSUE TITLE
Template for VIPER with RxCoordinator

### ISSUE THREAD

**Issue by YannickSteph** [quickbirdstudios/RxCoordinator#11]
Template for VIPER with RxCoordinator

I share with you my template VIPER with for your RxCoodinator. 

So i just begin the template.

https://github.com/pvp-technologies/Swift-VIPER-Module-Template

**Comment by grafele** [comment]
Wow. Thanks for your input.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
