### ISSUE TITLE
Transition between coordinators have problems with "whose view is not in the window hierarchy!"

### ISSUE THREAD

**Issue by lucio1392** [quickbirdstudios/RxCoordinator#15]
Hi,

I'm trying to change `initialRoute` depend on `business logic` but I got a problem with the warning `"whose view is not in the window hierarchy!"`

**The code blow taken from repo's example**

```
/// I have change from .Login to .Home at AppDelegate
coordinator = BasicCoordinator<MainRoute>(initialRoute: .home, initialLoadingType: .immediately) 

let window = UIWindow(frame: UIScreen.main.bounds)
window.rootViewController = coordinator.rootViewController
window.makeKeyAndVisible()
self.window = window
```
Then I got the error 
```Warning: Attempt to present <UINavigationController: 0x7face0815400> on <UINavigationController: 0x7face1822e00> whose view is not in the window hierarchy!```

Can some one tell me what cause this problems ? And how to fix this bug ?

**Comment by sellmair** [comment]
@pauljohanneskraft Related to #8 as far as I know.

**Comment by lucio1392** [comment]
@sellmair Sorry I don't get it.

**Comment by sellmair** [comment]
This issue is related to the MR #8.
@pauljohanneskraft Is working on it, as far as I know ☺️

**Comment by lucio1392** [comment]
@sellmair Ah, I see. Actually I still have some workaround for this situation but it's will be nicer if we can fix this bug with some good pattern.

**Comment by JeanVinge** [comment]
@lucio1392 i got the same problem, what did you do to solve? 
i'm using view code, the problem seen to not happen using xib, storyboard

**Comment by lucio1392** [comment]
@JeanVinge Hi man, this problem happen even you are using xib-storyboard or setup init on code.

My workaround just create 2 different Coordinator and check conditions, it's just about logic on code. 

Now I really don't have time to dive-in hope @pauljohanneskraft can fix this asap.

**Comment by grafele** [comment]
Hi. Thanks for your feedback. We will change this behavior in version 1.0. You can follow the process in the feature branches.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
