### ISSUE TITLE
Dismissal observable doesn't work properly for .push

### ISSUE THREAD

**Issue by Atimca** [quickbirdstudios/RxCoordinator#16]
Hello, thx for great framework! I bumped into one problem. When I use `.push` transition type dismissalObservable doesn't emit when I went back from navigation controller. I think that's because `viewController.isBeingDismissed` still `false` when `viewController.rx.sentMessage(#selector(UIViewController.viewWillDisappear))` emits.

**Comment by grafele** [comment]
Hi. Thanks for your feedback. We will change this behavior in version 1.0. You can follow the process in the feature branches.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
