### ISSUE TITLE
How to pass dependencies between modules?

### ISSUE THREAD

**Issue by SeRG1k17** [quickbirdstudios/RxCoordinator#19]
I see that this library took as a basis code from the RxSwift book. To me, this approach also seemed very laconic and clean. I see the main difference between your approach and the book. In the book, the authors propose to transfer the object of the viewModel in the enum case, you just pass the necessary data (string, number, etc.). The only option I see. add one more associated property to case. What do you think?

**Comment by grafele** [comment]
You can totally do that. We try to not force users to choose a specific option.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
