### ISSUE TITLE
How To Use RxCoordinator On UITabBarController

### ISSUE THREAD

**Issue by WuhooBigBoss** [quickbirdstudios/RxCoordinator#20]
I want to use RxCoordinator On UITabBarController, there is no introduce, please tell something about this, thanks

**Comment by WuhooBigBoss** [comment]
I see it from another issue, now is not support Tabbar , When will the official version be available?

**Comment by grafele** [comment]
Will be fixed in v1 release. You can use it already from the feat/v1 branch
