### ISSUE TITLE
How best to handle routes up the coordinator chain?

### ISSUE THREAD

**Issue by afrederick1** [quickbirdstudios/RxCoordinator#25]
Let's say I have a hierarchy of many Coordinators that are presented, and in the deepest level I then need to trigger a specific route defined at the root level which would do something like blow away the Coordinator hierarchy and all VCs for a different root route. Have you experimented with this use case? 

One approach I'm considering is defining a single Route type for the whole app, and sticking every single possible route in that one enum AppRoute, have all custom coordinators use it, then optionally inject a parent of AnyCoordinator<AppRoute> into each of my coordinators. When `prepareTransition` is called I'd implement only the routes that coordinator supports and in the .default case call `

```
parent?.trigger(route)
return .none()
```

Any other approaches I should consider?

I'm using the transition-rework branch too btw.

**Comment by pauljohanneskraft** [comment]
Hey @afrederick1, great to see you're interested in this framework!

To reduce the amount of cases in a Route-enum, I would suggest to use a custom RouteTrigger, which is translating the routes to a more generalized Route, as in the following:

```swift
enum HomeRoute: Route {
    case home
    case detail
}

enum AppRoute: Route {
    case home
    case push(Presentable)
}

class HomeRouteTrigger: RouteTrigger {
    let superCoordinator: AnyCoordinator<AppRoute>

    init(superCoordinator: AnyCoordinator<AppRoute>) {
        self.superCoordinator = superCoordinator
    }

    func trigger(_ route: HomeRoute, with options: TransitionOptions, completion: PresentationHandler?) {
        switch route {
        case .home:
            superCoordinator.trigger(.home, with: options, completion: completion)
        case .detail:
            superCoordinator.trigger(.push(detailViewController()), with: options, completion: completion)
        }
    }

    func detailViewController() -> UIViewController {
        fatalError("just used for demonstration")
    }
}
```

Alternatively, you could also just copy the enum cases into the child-routes, as in the following. With this approach, you will lose the completion handler and transitionOptions, which are then defined by the HomeRouteCoordinator.

```swift

enum HomeRoute: Route {
    case home
    case detail
}

enum AppRoute: Route {
    case home
    case push(Presentable)
}

class HomeRouteCoordinator: NavigationCoordinator<HomeRoute> {
    let superCoordinator: AnyCoordinator<AppRoute>

    init(superCoordinator: AnyCoordinator<AppRoute>) {
        self.superCoordinator = superCoordinator
        super.init(root: UIViewController())
    }

    override func prepareTransition(for route: HomeRoute) -> NavigationTransition {
        switch route {
        case .home:
            superCoordinator.trigger(.home)
            return .none()
        case .detail:
            return .push(detailViewController())
        }
    }

    func detailViewController() -> UIViewController {
        fatalError("just used for demonstration")
    }
}

```

With both of these two approaches, you can decrease coupling of individual components, as your HomeRoute does not need to know about any AppRoute, as the mapping only occurs in the HomeRouteTrigger or HomeRouteCoordinator.

**Comment by afrederick1** [comment]
Great thanks, I went with the second example you showed, inject the Router (formerly an AnyCoordinator) into any coordinator that needs to delegate route triggers up the chain. The only difference is I didn't duplicate the route name (in your example `.home`) across Routes, I'm sticking with a single global AppRoute, in our app you can jump to just about every route from anywhere.
