### ISSUE TITLE
Problems with the release/v1 pod installation

### ISSUE THREAD

**Issue by JFSene** [quickbirdstudios/RxCoordinator#29]
Hi there,

I was trying to use the branch where theres support for a TabbarController, but it seems that I am unable to install it, heres the error I get:

![image](https://user-images.githubusercontent.com/17616463/49155012-09384680-f301-11e8-8a02-631e00027d1e.png)

**Comment by afrederick1** [comment]
Hey @JFSene what does your Podfile look like for the repo? It should be something like this until the v1 branch is merged into master:

```
pod 'XCoordinator', :git => 'https://github.com/quickbirdstudios/RxCoordinator.git', :branch => 'feat/v1'
```

**Comment by GlebGamaunov** [comment]
> Hey @JFSene what does your Podfile look like for the repo? It should be something like this until the v1 branch is merged into master:
> 
> ```
> pod 'XCoordinator', :git => 'https://github.com/quickbirdstudios/RxCoordinator.git', :branch => 'feat/v1'
> ```

yep, great! that works

**Comment by thestreak88** [comment]
Any ideas how to get RxSwift extension? :)
`pod 'XCoordinator/RxSwift', '~> 1.0'`
this thing doesn't work

**Comment by adamsmaka** [comment]
Any ideas how to get RxSwift extension? :)
`pod 'XCoordinator/RxSwift', '~> 1.0'`
this thing doesn't work

**Comment by adamsmaka** [comment]
works! thank you so much. XCoordinator is awesome!
