### ISSUE TITLE
How to set Tabbar using RxCoordinator ?

### ISSUE THREAD

**Issue by xtcel** [quickbirdstudios/RxCoordinator#6]

**Comment by xtcel** [comment]
Hi grafele
I want to set UITabbarController to window root view controller,But coordinator root view controller always a UINavigationController type

**Comment by pauljohanneskraft** [comment]
We are currently working on making RxCoordinator more extensible, so that it also works for UITabBarController as well as future other customizations. You can take a look at this merge request here for more information: https://github.com/quickbirdstudios/RxCoordinator/pull/7.

**Comment by grafele** [comment]
Hi. Thanks for your feedback. We have added this feature to version 1.0. You can follow the process in the feature branches.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
